package dc2.view;


import dc2.model.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user
 */
public class AddPlaylistGUI extends javax.swing.JPanel {
    private PlaylistDirector pd;
    private PlaylistBuilder pb;
    private Playlist playlist;
    private File imageFile;
  //  private int sUserId;
    private DefaultTableModel newPlaylistModel;
    private ArrayList<Playlist> allPlaylists;
    private ArrayList<Song> newPlaylistSongList= new ArrayList<>();
    private SongDirector sd;
    private boolean def = false;
    Connection con;
   private int userId;
    /**
     * 
     * 
     * Creates new form AddMusicGUI
     * @param playlists
     * @param allPlaylists
     * @param sCreatorUsername
     */
    
    public AddPlaylistGUI(ArrayList<Playlist> playlists, int curuserID) {
       // NewPlaylistsSongTable.setModel(newPlaylistModel);
        initComponents();
        createConnection();
        userId= curuserID;
       allPlaylists= playlists;
       System.out.println(allPlaylists.get(0).getsPlaylistName());
    }
void createConnection(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/" + "playlistdb" + "?autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Hong_Kong", "root", "Dacadedust4444"
            );
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PlaylistNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlaylistDescriptionTextArea = new javax.swing.JTextArea();
        CancelAddPlaylistButton = new javax.swing.JButton();
        AddPlaylistButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PreviewPlaylistCoverLabel = new javax.swing.JLabel();
        SetPlaylistImageButton = new javax.swing.JButton();

        jLabel1.setText("Description");

        jLabel2.setText("Playlist Name:");

        PlaylistDescriptionTextArea.setColumns(20);
        PlaylistDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(PlaylistDescriptionTextArea);

        CancelAddPlaylistButton.setText("Cancel");
        CancelAddPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAddPlaylistButtonActionPerformed(evt);
            }
        });

        AddPlaylistButton.setText("Add");
        AddPlaylistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlaylistButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Playlist Cover Image:");

        SetPlaylistImageButton.setText("Set Image");
        SetPlaylistImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPlaylistImageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(PlaylistNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddPlaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelAddPlaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PreviewPlaylistCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetPlaylistImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlaylistNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PreviewPlaylistCoverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SetPlaylistImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelAddPlaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddPlaylistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlaylistButtonActionPerformed
        // TODO add your handling code here:
        pd = new PlaylistDirector();
        pb = new StandardPlaylistBuild();
        
        pd.setPlaylistBuilder(pb);
        pd.constructPlaylist(PlaylistNameTextField.getText(), PlaylistDescriptionTextArea.getText(), imageFile.getAbsolutePath(), userId, newPlaylistSongList, def);
        allPlaylists.add(pd.getPlaylist());
        try {
            PreparedStatement stmt = con.prepareStatement("INSERT INTO playlist(playlistTitle,playlistDescrpt, accountId, pictureFilePath, userCreated)Values(?,?,?,?,?)");
            stmt.setString(1, PlaylistNameTextField.getText());
            stmt.setString(2, PlaylistDescriptionTextArea.getText() );
             stmt.setInt(3, userId);
              stmt.setString(4, imageFile.getAbsolutePath() );
             stmt.setBoolean(5, true);
            
            stmt.executeUpdate();
            stmt.close();
        
       
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AddPlaylistButtonActionPerformed

    private void CancelAddPlaylistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAddPlaylistButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelAddPlaylistButtonActionPerformed

    private void SetPlaylistImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPlaylistImageButtonActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser filechooser = new JFileChooser();

            int retval = filechooser.showOpenDialog(null);
            if (retval == JFileChooser.APPROVE_OPTION) {
                
                imageFile = filechooser.getSelectedFile();
                ImageIcon imageIcon = new ImageIcon(imageFile.getAbsolutePath()); // load the image to a imageIcon
Image image = imageIcon.getImage(); // transform it 
Image newimg = image.getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
imageIcon = new ImageIcon(newimg);
                System.out.println(imageFile.getAbsolutePath());
                PreviewPlaylistCoverLabel.setIcon(imageIcon);
            }

        } catch (Exception e) {
            Logger.getLogger(AddPlaylistGUI.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_SetPlaylistImageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPlaylistButton;
    private javax.swing.JButton CancelAddPlaylistButton;
    private javax.swing.JTextArea PlaylistDescriptionTextArea;
    private javax.swing.JTextField PlaylistNameTextField;
    private javax.swing.JLabel PreviewPlaylistCoverLabel;
    private javax.swing.JButton SetPlaylistImageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
