/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dc2.view;

import dc2.model.PlayerBuild;
import dc2.model.Playlist;
import dc2.model.Song;
import dc2.model.SongBuilder;
import dc2.model.SongDirector;
import java.net.MalformedURLException;
import java.net.URL;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;
import dc2.model.account;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class MusicPlayerGUI extends javax.swing.JPanel {
    
    BasicPlayer player = new BasicPlayer();
    SongDirector sd = new SongDirector();
    SongBuilder sb = new PlayerBuild();
    account user;
    ArrayList<Playlist> playlists;
    private ArrayList<Song> songs;
    private int index;
    boolean blnVolume = false;
    boolean blnPaused = false;
    boolean blnOpened = false;

    /**
     * Creates new form MusicPlayerGUI
     * @param user
     */
    public MusicPlayerGUI(account User, ArrayList<Playlist> playlist) {
        initComponents();
        user=User;
        System.out.println(user.getAccountId());
        Username.setText("Account:"+ user.getusername());
        playlists= playlist;
        System.out.println(playlists.get(0).getsPlaylistName());
        ArrayList<Song> songList = new ArrayList<Song>();
        songList = playlists.get(0).getSongList();
        this.songs = songList;
        System.out.println(songList.get(0).getFilePath());
          System.out.println(songList.get(0).getAlbumName());
             System.out.println(songList.get(0).getYearReleased());
        System.out.println(songList.get(0).getGenre());
        
        //viewSongs.setValueAt("Test", 0, 0); add that to row 0 column zero
        for(int i = 0; i < songList.size(); i++) {
            int year = songList.get(i).getYearReleased();
            String strYear = Integer.toString(year);
            viewSongs.setValueAt(songList.get(i).getTitle(), i, 0);
            viewSongs.setValueAt(songList.get(i).getArtist(), i, 1);
            viewSongs.setValueAt(songList.get(i).getAlbumName(), i, 2);
            viewSongs.setValueAt(strYear, i, 3);
            viewSongs.setValueAt(songList.get(i).getGenre(), i, 4);
        }
       volumeSlider.setMinimum(0);
       volumeSlider.setMaximum(100);
       volumeSlider.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewSongs = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnPlayPause = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        volumeSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        changeVolume = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        playerTitle = new javax.swing.JLabel();
        playerArtist = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PlaylistCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        playlistTable = new javax.swing.JTable();

        setLayout(null);

        jButton1.setText("Create New Playlist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(10, 678, 142, 69);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Playlists");
        add(jLabel1);
        jLabel1.setBounds(10, 11, 125, 73);

        jButton2.setText("Delete Playlist");
        add(jButton2);
        jButton2.setBounds(10, 758, 125, 69);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("*replace this with playlist name*");
        add(jLabel2);
        jLabel2.setBounds(200, 90, 461, 22);

        viewSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Song Title", "Artist", "Album", "Year Released", "Genre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewSongs);

        add(jScrollPane2);
        jScrollPane2.setBounds(160, 310, 1120, 268);

        jLayeredPane1.setBackground(new java.awt.Color(222, 218, 218));
        jLayeredPane1.setOpaque(true);

        btnPlayPause.setText("Play");
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        jButton4.setText(">>");

        jButton5.setText("<<");

        jLabel3.setText("Volume");

        changeVolume.setText("Change");
        changeVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeVolumeActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(btnPlayPause, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(volumeSlider, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(changeVolume, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnPause, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnStop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3))
                    .addComponent(changeVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volumeSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeVolume)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPause, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(btnPlayPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))))
        );

        add(jLayeredPane1);
        jLayeredPane1.setBounds(400, 590, 749, 149);

        jLayeredPane2.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane2.setOpaque(true);

        playerTitle.setText("Song Title");

        playerArtist.setText("Artist");

        jLayeredPane2.setLayer(playerTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(playerArtist, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerArtist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );

        add(jLayeredPane2);
        jLayeredPane2.setBounds(210, 590, 180, 146);

        jLabel9.setText("Playlist Description");
        add(jLabel9);
        jLabel9.setBounds(495, 406, 473, 59);

        PlaylistCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default Playlists", "User Playlists", "Favorite Playlists" }));
        PlaylistCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaylistComboActionPerformed(evt);
            }
        });
        add(PlaylistCombo);
        PlaylistCombo.setBounds(10, 93, 125, 22);

        jLabel8.setText("Playlist Photo");
        add(jLabel8);
        jLabel8.setBounds(170, 120, 215, 173);

        jLabel12.setText("by");
        add(jLabel12);
        jLabel12.setBounds(540, 90, 440, 25);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Playlist description");
        jScrollPane3.setViewportView(jTextArea1);

        add(jScrollPane3);
        jScrollPane3.setBounds(380, 120, 478, 173);

        jButton3.setText("Add Song to Playlist");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(1010, 120, 172, 70);

        jButton8.setText("Remove Song from Playlist");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(1010, 200, 172, 66);

        jButton9.setText("Delete Song");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9);
        jButton9.setBounds(1190, 200, 108, 66);

        jButton10.setText("Upload Song");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10);
        jButton10.setBounds(1190, 130, 108, 60);

        Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Username.setText("Username");
        add(Username);
        Username.setBounds(220, 20, 418, 50);

        playlistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Playlists"
            }
        ));
        jScrollPane4.setViewportView(playlistTable);

        add(jScrollPane4);
        jScrollPane4.setBounds(10, 180, 130, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPauseActionPerformed
        // TODO add your handling code here:
        if(blnPaused == false && blnOpened == false) {
        int row = viewSongs.getSelectedRow();
        String title = String.valueOf(viewSongs.getValueAt(row, 0));
        
        for (int i = 0; i < songs.size(); i++) {
            if(songs.get(i).getTitle().equals(title))
                index = i;
        }
        
        String filepath = songs.get(index).getFilePath();
        sd.setSongBuilder(sb);
        sd.constructSong("null", "null", "null", 0, "null", filepath);
        Song song = sd.getSong();
        try {
           player.open(new URL("file:///" + song.getFilePath()));
           player.play();
           playerTitle.setText(songs.get(index).getTitle());
           playerArtist.setText(songs.get(index).getArtist());
        }catch (BasicPlayerException | MalformedURLException e) {
            e.printStackTrace();
        }
        blnOpened = true;
        }
        if(blnPaused == true) {
            try {
                player.resume();
                blnPaused = false;
            }catch(BasicPlayerException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void PlaylistComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistComboActionPerformed
        DefaultTableModel model = (DefaultTableModel) playlistTable.getModel();; 
        DefaultTableModel model2 = (DefaultTableModel) playlistTable.getModel();; 
        if(PlaylistCombo.getSelectedIndex()== 0){
       
  
            playlistTable.setValueAt("All Songs", 1, 0);
            playlistTable.setValueAt("Favorites", 2, 0);
           
 
        }
        else{
              
  playlistTable.setValueAt("UserCreated", 1, 0);

  

    }
    }//GEN-LAST:event_PlaylistComboActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       JFrame frame = new JFrame();
       frame.getContentPane().add(new UploadSong());
       frame.setVisible(true);
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       frame.pack();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFrame frame = new JFrame();
      frame.getContentPane().add(new AddPlaylistGUI(playlists, user.getAccountId()));
      frame.setVisible(true);
       frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      frame.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void changeVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeVolumeActionPerformed
        // TODO add your handling code here:
        int temp = volumeSlider.getValue();
        double value = Double.valueOf(temp) / 100;
        
        try {
            player.setGain(value);
        }catch(BasicPlayerException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_changeVolumeActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:   
        if(blnPaused == false) {
            try {
                player.pause();
                blnPaused = true;
            }catch(BasicPlayerException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        try{
            player.stop();
        }catch(BasicPlayerException e) {
            e.printStackTrace();
        }
        blnOpened = false;
    }//GEN-LAST:event_btnStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PlaylistCombo;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton changeVolume;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel playerArtist;
    private javax.swing.JLabel playerTitle;
    private javax.swing.JTable playlistTable;
    private javax.swing.JTable viewSongs;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables
}
